version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk8
        python: 3.7
    commands:
      -  pip install --upgrade pip
      -  pip install --upgrade 'pyyaml < 6.0'
      -  pip install --upgrade 'six==1.15.0'
      -  pip install boto3 --upgrade
      -  pip install --upgrade 'docker~=4.0'
      -  pip install --upgrade 'importlib-metadata==6.6.0'
      -  pip install --upgrade 'aws-sam-translator==1.22.0'
      -  pip install pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - pre-commit run --all-files
      - cd "$CODEBUILD_SRC_DIR/aws-customerprofiles-domain"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-customerprofiles-integration"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-customerprofiles-objecttype"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-customerprofiles-calculatedattributedefinition"
      - mvn clean verify --no-transfer-progress
      - cd "$CODEBUILD_SRC_DIR/aws-customerprofiles-eventstream"
    finally:
      - cat "$CODEBUILD_SRC_DIR/aws-customerprofiles-domain/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-customerprofiles-integration/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-customerprofiles-objecttype/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-customerprofiles-calculatedattributedefinition/rpdk.log"
      - cat "$CODEBUILD_SRC_DIR/aws-customerprofiles-eventstream/rpdk.log"